spring:
  application:
    name: ad-filters-subscriber
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 6 #警告阈值, 原始规则长度小于该值时会输出警告日志

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:
    #远程订阅规则 （！使用前请删除下方示例配置, 注意缩进）
    remote:
      - name: 'Additional Filters CN'
        path: 'https://github.com/Crystal-RainSlide/AdditionalFiltersCN/raw/master/CN.txt'
      - name: 'Additional Filters Intl'
        path: 'https://github.com/Crystal-RainSlide/AdditionalFiltersCN/raw/master/Intl.txt'
      - name: 'Additional Filters Other'
        path: 'https://github.com/Crystal-RainSlide/AdditionalFiltersCN/raw/master/RainSlide.txt'
      - name: 'Adguard Annyoyances optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/14_optimized.txt'
      - name: 'Adguard Chinese filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_224_Chinese/filter.txt'
      - name: 'Adguard DNS filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_15_DnsFilter/filter.txt'
      - name: 'Adguard Experimental filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_5_Experimental/filter.txt'
      - name: 'Adguard Mobile Ads filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_11_Mobile/filter.txt'
      - name: 'Adguard Social Media filter'
        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_4_Social/filter.txt'
      - name: 'Adguard Social Media filter optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/4_optimized.txt'
#      - name: 'Adguard Tracking Protection filter'
#        path: 'https://filters.adtidy.org/extension/ublock/filters/3.txt'
#      - name: 'Adguard URL Tracking Parameters filter'
#        path: 'https://github.com/AdguardTeam/FiltersRegistry/raw/master/filters/filter_17_TrackParam/filter.txt'
      - name: 'AdRules AdBlock List Plus Cats-Team'
        path: 'https://github.com/Cats-Team/AdRules/raw/main/adblock_plus.txt'
      - name: 'AdRules AdBlock DNS List Plus Cats-Team'
        path: 'https://github.com/Cats-Team/AdRules/raw/main/dns.txt'
      - name: 'ad-wars'
        path: 'https://github.com/jdlingyu/ad-wars/raw/master/hosts'
      - name: 'anti-AD for AdGuard'
        path: 'https://github.com/privacy-protection-tools/anti-AD/raw/master/anti-ad-adguard.txt'
      - name: 'AWAvenue-Ads-Rule'
        path: 'https://github.com/TG-Twilight/AWAvenue-Ads-Rule/raw/main/AWAvenue-Ads-Rule.txt'
      - name: 'Block HTTP DNS'
        path: 'https://github.com/blackmatrix7/ios_rule_script/raw/release/rule/AdGuard/BlockHttpDNS/BlockHttpDNS.txt'
      - name: 'bypass-paywalls-clean-filters'
        path: 'https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/raw/main/bpc-paywall-filter.txt'
      - name: 'Dandelion Sprouts Annoyances List'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/AnnoyancesList'
      - name: 'DandelionSprout Social Media & Share Filter List'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/SocialShareList.txt'
      - name: 'Dandelion Sprouts Browse Websites Without Logging In'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/BrowseWebsitesWithoutLoggingIn.txt' 
      - name: 'DD-AD'
        path: 'https://github.com/afwfv/DD-AD/raw/main/rule/DD-AD.txt'      
      - name: 'EasyList + AdGuard Base filter Optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/2_optimized.txt'
      - name: 'EasyList Chat Widgets'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-chat.txt'
      - name: 'EasyList Cookie List'
        path: 'https://ublockorigin.pages.dev/thirdparties/easylist-cookies.txt'
      - name: 'EasyList Newsletter List'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-newsletters.txt'
      - name: 'EasyList Notifications List'
        path: 'https://ublockorigin.pages.dev/thirdparties/easylist-notifications.txt'
      - name: 'EasyList Other Annoyances List'
        path: 'https://cdn.statically.io/gh/uBlockOrigin/uAssetsCDN/main/thirdparties/easylist-annoyances.txt'
      - name: 'EasyList Social List'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/thirdparties/easylist-social.txt'
      - name: 'Fanboy Annoyances optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/122_optimized.txt'
      - name: 'HaGeZis Ultimate DNS Blocklist'
        path: 'https://github.com/hagezi/dns-blocklists/raw/main/adblock/ultimate.txt'
      - name: 'hblock'
        path: 'https://hblock.molinero.dev/hosts_adblock.txt'
      - name: 'HalfLife ad block list'
        path: 'https://github.com/o0HalfLife0o/list/raw/master/ad-pc.txt'
      - name: 'I Dont Care About Cookies'
        path: 'https://www.i-dont-care-about-cookies.eu/abp/'
#     - name: 'Legitimate URL Shortener List'
#       path: 'https://github.com/DandelionSprout/adfilt/raw/master/LegitimateURLShortener.txt'
      - name: 'No App Download'
        path: 'https://github.com/Noyllopa/NoAppDownload/raw/master/NoAppDownload.txt'
      - name: 'Oisd Big'
        path: 'https://big.oisd.nl/'
      - name: 'Peter Lowes Ad and tracking server list'
        path: 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=0&startday=01&startmonth=01&startyear=2000&mimetype=plaintext'
      - name: 'Twitch: Pure Viewing Experience'
        path: 'https://github.com/DandelionSprout/adfilt/raw/master/TwitchPureViewing' 
      - name: 'uBlock Filters - AD'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/filters.min.txt'
      - name: 'uBlock Filters - Annoyances'
        path: 'https://ublockorigin.pages.dev/filters/annoyances.min.txt'
      - name: 'uBlock Filters - Annoyances optimized'
        path: 'https://filters.adtidy.org/extension/ublock/filters/101_optimized.txt'
      - name: 'uBlock Filters - Cookie Notices'
        path: 'https://ublockorigin.github.io/uAssetsCDN/filters/annoyances-cookies.txt'
      - name: 'uBlock Filters - Privacy'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/privacy.min.txt'
      - name: 'uBlock Filters - Quick Fixes'
        path: 'https://cdn.jsdelivr.net/gh/uBlockOrigin/uAssetsCDN@main/filters/quick-fixes.min.txt'
      - name: 'uBlock Filters - Unbreak'
        path: 'https://ublockorigin.pages.dev/filters/unbreak.min.txt'
      - name: 'yokoffing annoyance list'
        path: 'https://github.com/yokoffing/filterlists/raw/main/annoyance_list.txt'
      - name: 'yokoffing block third party fonts'
        path: 'https://github.com/yokoffing/filterlists/raw/main/block_third_party_fonts.txt'
      - name: 'yhosts'
        path: 'https://github.com/VeleSila/yhosts/raw/master/hosts.txt'
#     - name: '1Host Pro'
#       path: 'https://o0.pages.dev/Pro/adblock.txt'
      - name: '奶酪 网页水印过滤规则'
        path: 'https://github.com/runningcheese/RunningCheese-Firefox/raw/master/Restore/Adblock_Watermark.txt'
      - name: '奶酪 网页弹窗过滤规则'
        path: 'https://github.com/runningcheese/RunningCheese-Firefox/raw/master/Restore/Adblock_Popup.txt'

    #本地规则文件
    local:
      - name: 'Personal Block List'
        path: 'rule/personal-block-list.txt' #支持绝对/相对路径

  #输出配置
  output:
    #生成的规则文件头部内容, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
    file_header: |
      [ADFS Adblock List]
      ! Title: AdBlock List - ${name}
      ! Description: Compilation of Some Most Used AdBlock Lists
      ! TimeUpdated: ${date}
      ! Homepage: https://github.com/fliappybird/AD-Block

    path: rule #输出规则文件的路径，支持绝对/相对路径
    #输出规则文件列表 （！注意缩进）
    files:
#      all.txt: #输出文件名
#         - DOMAIN  #域名规则，仅完整域名
#         - REGEX   #正则规则，包含正则的域名规则
#         - MODIFY  #修饰规则，添加了一些修饰符号的规则
#         - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
#      hosts.txt:
#        - HOSTS
#      regex.txt:
#        - REGEX
#      domain.txt:
#        - DOMAIN
      modify.txt:
        - MODIFY
